name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'pound_front/**'

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: pound_front/yarn.lock

    - name: Install dependencies
      run: |
        cd pound_front
        yarn install

    - name: Build
      run: |
        cd pound_front
        yarn build

    - name: Get S3 bucket name
      id: get-bucket
      run: |
        BUCKET_NAME=$(aws cloudformation describe-stacks \
          --stack-name pound-app-prod-frontend \
          --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
          --output text)
        echo "bucket=$BUCKET_NAME" >> $GITHUB_OUTPUT

    - name: Upload to S3
      run: |
        cd pound_front
        aws s3 sync out/ s3://${{ steps.get-bucket.outputs.bucket }}/ --delete

    - name: Invalidate CloudFront
      run: |
        DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
          --stack-name pound-app-prod-frontend \
          --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
          --output text)
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"